"""Fundament: SDE-, ESI- und App-Tabellen

Revision ID: 0001_fundament
Revises: 
Create Date: 2026-09-07 04:32:13.201467
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_fundament"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('esi_http_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esi_http_cache'))
    )
    with op.batch_alter_table('esi_http_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_http_cache_cache_key'), ['cache_key'], unique=True)

    op.create_table('esi_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('unchanged', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('tokens_spent', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error_limit_remain', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esi_sync_runs'))
    )
    with op.batch_alter_table('esi_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_sync_runs_corporation_id'), ['corporation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_sync_runs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_sync_runs_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_sync_runs_route'), ['route'], unique=False)
        batch_op.create_index('ix_esi_sync_runs_route_started', ['route', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_sync_runs_started_at'), ['started_at'], unique=False)

    op.create_table('sde_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=32), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('max_production_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_blueprints'))
    )
    with op.batch_alter_table('sde_blueprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_blueprints_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_blueprints_blueprint_type_id'), ['blueprint_type_id'], unique=False)
        batch_op.create_index('ix_sde_blueprints_type_activity', ['blueprint_type_id', 'activity'], unique=True)

    op.create_table('sde_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('row_counts', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_builds')),
    sa.UniqueConstraint('build', name=op.f('uq_sde_builds_build'))
    )
    op.create_table('sde_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_sde_categories'))
    )
    with op.batch_alter_table('sde_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_categories_name'), ['name'], unique=False)

    op.create_table('sde_planet_schematics',
    sa.Column('schematic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cycle_time_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('schematic_id', name=op.f('pk_sde_planet_schematics'))
    )
    with op.batch_alter_table('sde_planet_schematics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_planet_schematics_name'), ['name'], unique=False)

    op.create_table('sde_regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk_sde_regions'))
    )
    with op.batch_alter_table('sde_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_regions_name'), ['name'], unique=False)

    op.create_table('sde_blueprint_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['sde_blueprints.id'], name=op.f('fk_sde_blueprint_materials_blueprint_id_sde_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_blueprint_materials'))
    )
    with op.batch_alter_table('sde_blueprint_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_blueprint_materials_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_blueprint_materials_type_id'), ['type_id'], unique=False)

    op.create_table('sde_blueprint_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['sde_blueprints.id'], name=op.f('fk_sde_blueprint_products_blueprint_id_sde_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_blueprint_products'))
    )
    with op.batch_alter_table('sde_blueprint_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_blueprint_products_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_blueprint_products_type_id'), ['type_id'], unique=False)

    op.create_table('sde_blueprint_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['sde_blueprints.id'], name=op.f('fk_sde_blueprint_skills_blueprint_id_sde_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_blueprint_skills'))
    )
    with op.batch_alter_table('sde_blueprint_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_blueprint_skills_blueprint_id'), ['blueprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_blueprint_skills_type_id'), ['type_id'], unique=False)

    op.create_table('sde_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sde_categories.category_id'], name=op.f('fk_sde_groups_category_id_sde_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_sde_groups'))
    )
    with op.batch_alter_table('sde_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_groups_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_groups_name'), ['name'], unique=False)

    op.create_table('sde_planet_schematic_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schematic_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schematic_id'], ['sde_planet_schematics.schematic_id'], name=op.f('fk_sde_planet_schematic_types_schematic_id_sde_planet_schematics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sde_planet_schematic_types'))
    )
    with op.batch_alter_table('sde_planet_schematic_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_planet_schematic_types_schematic_id'), ['schematic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_planet_schematic_types_type_id'), ['type_id'], unique=False)

    op.create_table('sde_systems',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('security_status', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['sde_regions.region_id'], name=op.f('fk_sde_systems_region_id_sde_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id', name=op.f('pk_sde_systems'))
    )
    with op.batch_alter_table('sde_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_systems_constellation_id'), ['constellation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_systems_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_systems_region_id'), ['region_id'], unique=False)

    op.create_table('sde_planets',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['sde_systems.system_id'], name=op.f('fk_sde_planets_system_id_sde_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planet_id', name=op.f('pk_sde_planets'))
    )
    with op.batch_alter_table('sde_planets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_planets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_planets_system_id'), ['system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_planets_type_id'), ['type_id'], unique=False)

    op.create_table('sde_stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['sde_systems.system_id'], name=op.f('fk_sde_stations_system_id_sde_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id', name=op.f('pk_sde_stations'))
    )
    with op.batch_alter_table('sde_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_stations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_stations_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_stations_system_id'), ['system_id'], unique=False)

    op.create_table('sde_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('packaged_volume', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('portion_size', sa.Integer(), nullable=False),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sde_groups.group_id'], name=op.f('fk_sde_types_group_id_sde_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', name=op.f('pk_sde_types'))
    )
    with op.batch_alter_table('sde_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_types_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_types_market_group_id'), ['market_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_types_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sde_types_published'), ['published'], unique=False)
        batch_op.create_index('ix_sde_types_published_name', ['published', 'name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sde_types', schema=None) as batch_op:
        batch_op.drop_index('ix_sde_types_published_name')
        batch_op.drop_index(batch_op.f('ix_sde_types_published'))
        batch_op.drop_index(batch_op.f('ix_sde_types_name'))
        batch_op.drop_index(batch_op.f('ix_sde_types_market_group_id'))
        batch_op.drop_index(batch_op.f('ix_sde_types_group_id'))

    op.drop_table('sde_types')
    with op.batch_alter_table('sde_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_stations_system_id'))
        batch_op.drop_index(batch_op.f('ix_sde_stations_region_id'))
        batch_op.drop_index(batch_op.f('ix_sde_stations_name'))

    op.drop_table('sde_stations')
    with op.batch_alter_table('sde_planets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_planets_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_planets_system_id'))
        batch_op.drop_index(batch_op.f('ix_sde_planets_name'))

    op.drop_table('sde_planets')
    with op.batch_alter_table('sde_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_systems_region_id'))
        batch_op.drop_index(batch_op.f('ix_sde_systems_name'))
        batch_op.drop_index(batch_op.f('ix_sde_systems_constellation_id'))

    op.drop_table('sde_systems')
    with op.batch_alter_table('sde_planet_schematic_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_planet_schematic_types_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_planet_schematic_types_schematic_id'))

    op.drop_table('sde_planet_schematic_types')
    with op.batch_alter_table('sde_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_groups_name'))
        batch_op.drop_index(batch_op.f('ix_sde_groups_category_id'))

    op.drop_table('sde_groups')
    with op.batch_alter_table('sde_blueprint_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_skills_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_skills_blueprint_id'))

    op.drop_table('sde_blueprint_skills')
    with op.batch_alter_table('sde_blueprint_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_products_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_products_blueprint_id'))

    op.drop_table('sde_blueprint_products')
    with op.batch_alter_table('sde_blueprint_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_materials_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_blueprint_materials_blueprint_id'))

    op.drop_table('sde_blueprint_materials')
    with op.batch_alter_table('sde_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_regions_name'))

    op.drop_table('sde_regions')
    with op.batch_alter_table('sde_planet_schematics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_planet_schematics_name'))

    op.drop_table('sde_planet_schematics')
    with op.batch_alter_table('sde_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_categories_name'))

    op.drop_table('sde_categories')
    op.drop_table('sde_builds')
    with op.batch_alter_table('sde_blueprints', schema=None) as batch_op:
        batch_op.drop_index('ix_sde_blueprints_type_activity')
        batch_op.drop_index(batch_op.f('ix_sde_blueprints_blueprint_type_id'))
        batch_op.drop_index(batch_op.f('ix_sde_blueprints_activity'))

    op.drop_table('sde_blueprints')
    with op.batch_alter_table('esi_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_sync_runs_started_at'))
        batch_op.drop_index('ix_esi_sync_runs_route_started')
        batch_op.drop_index(batch_op.f('ix_esi_sync_runs_route'))
        batch_op.drop_index(batch_op.f('ix_esi_sync_runs_owner_type'))
        batch_op.drop_index(batch_op.f('ix_esi_sync_runs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_esi_sync_runs_corporation_id'))

    op.drop_table('esi_sync_runs')
    with op.batch_alter_table('esi_http_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_http_cache_cache_key'))

    op.drop_table('esi_http_cache')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
