"""Charaktere, Tokens, Rollen und Bestaende

Revision ID: 0002_login_und_bestaende
Revises: 0001_fundament
Create Date: 2026-09-07 15:01:22.858870
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_login_und_bestaende"
down_revision: str | None = "0001_fundament"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esi_asset_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('root_location_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=True),
    sa.Column('quantity_after', sa.Integer(), nullable=True),
    sa.Column('location_before', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esi_asset_changes'))
    )
    with op.batch_alter_table('esi_asset_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_corporation_id'), ['corporation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_esi_asset_changes_owner_observed', ['owner_type', 'owner_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_asset_changes_type_id'), ['type_id'], unique=False)

    op.create_table('esi_assets',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_flag', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('is_blueprint_copy', sa.Boolean(), nullable=False),
    sa.Column('root_location_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_esi_assets'))
    )
    with op.batch_alter_table('esi_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_assets_corporation_id'), ['corporation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_location_flag'), ['location_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index('ix_esi_assets_owner_type_id', ['owner_type', 'owner_id', 'type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_root_location_id'), ['root_location_id'], unique=False)
        batch_op.create_index('ix_esi_assets_root_type', ['root_location_id', 'type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_assets_type_id'), ['type_id'], unique=False)

    op.create_table('esi_characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('owner_hash', sa.String(length=128), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_esi_characters'))
    )
    with op.batch_alter_table('esi_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_characters_alliance_id'), ['alliance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_characters_corporation_id'), ['corporation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_characters_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_esi_characters_status'), ['status'], unique=False)

    op.create_table('esi_structures',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('owner_corporation_id', sa.Integer(), nullable=True),
    sa.Column('access_denied', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('structure_id', name=op.f('pk_esi_structures'))
    )
    with op.batch_alter_table('esi_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esi_structures_system_id'), ['system_id'], unique=False)

    op.create_table('esi_character_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['esi_characters.character_id'], name=op.f('fk_esi_character_roles_character_id_esi_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_esi_character_roles'))
    )
    with op.batch_alter_table('esi_character_roles', schema=None) as batch_op:
        batch_op.create_index('ix_esi_character_roles_char_role', ['character_id', 'scope', 'role'], unique=True)
        batch_op.create_index(batch_op.f('ix_esi_character_roles_character_id'), ['character_id'], unique=False)

    op.create_table('esi_character_tokens',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('storage', sa.String(length=32), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['esi_characters.character_id'], name=op.f('fk_esi_character_tokens_character_id_esi_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_esi_character_tokens'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esi_character_tokens')
    with op.batch_alter_table('esi_character_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_character_roles_character_id'))
        batch_op.drop_index('ix_esi_character_roles_char_role')

    op.drop_table('esi_character_roles')
    with op.batch_alter_table('esi_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_structures_system_id'))

    op.drop_table('esi_structures')
    with op.batch_alter_table('esi_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_characters_status'))
        batch_op.drop_index(batch_op.f('ix_esi_characters_name'))
        batch_op.drop_index(batch_op.f('ix_esi_characters_corporation_id'))
        batch_op.drop_index(batch_op.f('ix_esi_characters_alliance_id'))

    op.drop_table('esi_characters')
    with op.batch_alter_table('esi_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_assets_type_id'))
        batch_op.drop_index('ix_esi_assets_root_type')
        batch_op.drop_index(batch_op.f('ix_esi_assets_root_location_id'))
        batch_op.drop_index('ix_esi_assets_owner_type_id')
        batch_op.drop_index(batch_op.f('ix_esi_assets_owner_type'))
        batch_op.drop_index(batch_op.f('ix_esi_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_esi_assets_location_id'))
        batch_op.drop_index(batch_op.f('ix_esi_assets_location_flag'))
        batch_op.drop_index(batch_op.f('ix_esi_assets_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_esi_assets_corporation_id'))

    op.drop_table('esi_assets')
    with op.batch_alter_table('esi_asset_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_type_id'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_owner_type'))
        batch_op.drop_index('ix_esi_asset_changes_owner_observed')
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_observed_at'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_kind'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_job_id'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_item_id'))
        batch_op.drop_index(batch_op.f('ix_esi_asset_changes_corporation_id'))

    op.drop_table('esi_asset_changes')
    # ### end Alembic commands ###
